### ISSUE TITLE
Cannot install web-app-theme with Ruby 1.9.1

### ISSUE THREAD

**Issue by chillicoder** [gravityblast/web-app-theme#3]
There seems to be a problem when installing web-app-theme as a plugin with Ruby 1.9.

`Macintosh:demo19 martin$ script/plugin install git://github.com/pilu/web-app-theme.git`

`Plugin not found: ["git://github.com/pilu/web-app-theme.git"]`

`Macintosh:demo19 martin$ ls vendor//plugins/`

`web-app-theme`

`Macintosh:demo19 martin$ ls vendor//plugins/web-app-theme/`

`Macintosh:demo19 martin$`

**Comment by zacheryph** [comment]
this is a rails+ruby 1.9 error and happens with all plugins with a git url. this is not a web-app-theme error.  this is fixed in rails edge and will be in the 2.3.5 release. here is the ticket related:

https://rails.lighthouseapp.com/projects/8994/tickets/2018-ruby-19-compat-plugininstall-git-always-fails-in-ruby-19

this issue is closable.

**Comment by gravityblast** [comment]
Thank you for the information. I'm going to close the issue

**Comment by chillicoder** [comment]
Thank you all. :D
